service: default

runtime: go
api_version: go1

env_variables:
  APPENGINE_ENABLED: 'true'
  STRAVA_CLIENT_ID: '${STRAVA_CLIENT_ID}'
  STRAVA_CLIENT_SECRET: '${STRAVA_CLIENT_SECRET}'
  ROOT_URL: '${ROOT_URL}'
  STRAVA_CACHE_IMPL: '${STRAVA_CACHE_IMPL}'
  STRAVA_CACHE_ROOT: '${STRAVA_CACHE_ROOT}'
  ZONES_ENABLED: '%{ZONES_ENABLED}'

handlers:
- url: /.*
  script: _go_app